#!/bin/bash
#
# Based on https://gist.github.com/1002667
#
# Usage: place in <project root>/.git/hooks, must be named post-commit, must be chmod +x

# executable paths
GREP="/usr/bin/grep"
CUT="/usr/bin/cut"
JEKYLL="/Users/jim/.rvm/gems/ruby-1.9.2-p290@jamesferguson.github.com/bin/jekyll"
GIT="/usr/local/git/bin/git"
RM="/bin/rm"
CP="/bin/cp"

PROJ_ROOT="$($GIT rev-parse --show-toplevel)"

# Config
JEKYLL_OPTIONS=(--no-safe --no-server --no-auto)

SRC_BRANCH="develop"
PUBLISH_BRANCH="master"

function publish() {

  # the current branch
  CURRENT_BRANCH="$($GREP "^*" < <("$GIT" branch) | $CUT -d' ' -f2)"

  # only publish if this commit was made on SRC_BRANCH
  if [[ $CURRENT_BRANCH == $SRC_BRANCH ]]; then

    # Don't assume we'll lazily commit all changes at once
    "$GIT" add . # ensure even untracked files are stashed
    "$GIT" stash

    # generate the site to temp dir
    cd $PROJ_ROOT
    TMP_SITE_DIR="$("/usr/bin/mktemp" -d /tmp/_site.XXXXXXXXX)" # directory holding the generated site -- should be outside this repo
    "$JEKYLL" ${JEKYLL_OPTIONS[@]} . "$TMP_SITE_DIR"

    "$GIT" checkout "$PUBLISH_BRANCH"

    # overwrite existing files
    builtin shopt -s dotglob
    "$CP" -rf "$TMP_SITE_DIR"/* .
    builtin shopt -u dotglob

    "$GIT" add .
    "$GIT" commit -a -m "updated site @ $(date +"%F %T")"

    # cleanup and restore
    "$RM" -rfv "$TMP_SITE_DIR"
    "$GIT" checkout "$SRC_BRANCH"
    "$GIT" stash pop
  fi
}

publish | tee "$PROJ_ROOT/_hooks/log/post-commit.log"

