#!/bin/bash
#
# Based on https://gist.github.com/1002667
#
# Usage: place in <project root>/.git/hooks, must be named post-commit, must be chmod +x

# executable paths
GREP="/usr/bin/grep"
CUT="/usr/bin/cut"
JEKYLL="/Users/jim/.rvm/gems/ruby-1.9.2-p290@jamesferguson.github.com/bin/jekyll"
GIT="/usr/local/git/bin/git"
RM="/bin/rm"

PROJ_ROOT="$("$GIT" rev-parse --show-toplevel)"

# Config
JEKYLL_OPTIONS=(--no-safe --no-server --no-auto)

SRC_BRANCH="master"
PUBLISH_BRANCH="gh-pages"

# directory holding the generated site -- should be outside this repo
TMP_SITE_DIR="$("/usr/bin/mktemp" -d /tmp/_site.XXXXXXXXX)"


function publish() {

  # the current branch
  _currbranch="$($GREP "^*" < <("$GIT" branch) | $CUT -d' ' -f2)"

  if [[ $_currbranch == $SRC_BRANCH ]]; then # we should generate the site
      # go to root dir of the repo
      cd $PROJ_ROOT
      # generate the site
      "$JEKYLL" ${JEKYLL_OPTIONS[@]} . "$TMP_SITE_DIR"
      # switch to branch the site will be stored
      "$GIT" checkout "$PUBLISH_BRANCH"
      # overwrite existing files
      builtin shopt -s dotglob
      /bin/cp -rf "$TMP_SITE_DIR"/* .
      builtin shopt -u dotglob
      # add any new files
      "$GIT" add .
      # commit all changes with a default message
      "$GIT" commit -a -m "updated site @ $(date +"%F %T")"
      # cleanup
      "$RM -rfv $TMP_SITE_DIR"
      # return
      "$GIT" checkout "$SRC_BRANCH"
  fi
}

publish | tee "$PROJ_ROOT/_hooks/log/post-commit.log"

