auto:                 true
server:               true
server_port:          4000
                      
safe:                 false
lsi:                  false
                      
markdown:             maruku
pygments:             true
                      
source:               .
destination:          ./_site
exclude:              CNAME, Gemfile, Gemfile.lock, README, script, spec, tmp
permalink:            /:categories/:title
                      
url:                  http://j-ferguson.com/
name:                 simply coding
tagline:              Seek simplicity and distrust it.
tagline_attribution:  Alfred North Whitehead
jekyll_version:       0.11.2
stylesheet_url:       /css/site.css
atom_url:             /rss/atom.xml
